name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore AltenShop.sln

    - name: Build solution
      run: dotnet build AltenShop.sln --no-restore --configuration Release

    - name: Run unit tests
      run: dotnet test Api.UnitTests/Api.UnitTests.csproj --no-build --configuration Release --verbosity normal

    - name: Run integration tests
      run: dotnet test Api.IntegrationTests/Api.IntegrationTests.csproj --no-build --configuration Release --verbosity normal